language: php
install:
  - composer selfupdate
  - composer install
  - cp config/yapeal-example.yaml config/yapeal.yaml
matrix:
  allow_failures:
    - php: 7,hhvm
php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - hhvm

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
